# Generated by Django 6.0.7 on 2026-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlqlog',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dlqlog',
            name='exception_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dlqlog',
            name='task_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
