# Generated by Django 6.0.7 on 2026-07-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dlqlog_event_id_dlqlog_exception_type_dlqlog_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticslog',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
